baseURL = "https://www.davidsoff.nl/"
languageCode = "en-us"
title = "MagPie DevOps"
theme = "kiss"
copyright = "All Rights Reserved <a href=\"https://github.com/DavidSoff\">David Soff</a> 2019"
disqusShortname = "davidsoff-nl"
googleAnalytics = "UA-151064893-1"
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[author]
    name = "David Soff"

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "David Soff" # Author full name
authorEmail = "david@soff.nl" # Author email

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Home" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks

[params.features]
disqusOnDemand = true

[params.social]
twitter = "SoffDavid"
github = "DavidSoff"
email = "david@soff.nl"
linkedin = "davidsoff"
rss = "index.xml"

[params.social.config]
platforms = ["github","twitter","email","linkedin", "rss"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

[params.assets]
customCSS = ["css/index.css", "css/presentation.css"]